# Generated by Django 6.0.7 on 2026-08-22 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زیرمنو')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('is_available', models.BooleanField(default=True, verbose_name='قابل سفارش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.menuitem', verbose_name='آیتم منو')),
            ],
            options={
                'verbose_name': 'زیرمنو',
                'verbose_name_plural': 'زیرمنوها',
                'ordering': ['menu_item', 'id'],
                'constraints': [models.UniqueConstraint(fields=('menu_item', 'name'), name='unique_menu_item_variant')],
            },
        ),
    ]
