# Generated by Django 6.0.7 on 2026-08-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
    ]
