# Generated by Django 6.0.7 on 2026-08-22 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_employee_national_code_alter_role_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('salary', 'پرداخت حقوق'), ('receivable', 'دریافت طلب'), ('expense', 'هزینه'), ('raw_material', 'خرید مواد اولیه'), ('repair', 'تعمیرات'), ('damage', 'خسارت'), ('delivery', 'پیک'), ('withdrawal', 'برداشت'), ('other_income', 'سایر درآمدها'), ('other_expense', 'سایر هزینه\u200cها')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقدی'), ('card', 'کارت بانکی'), ('card_to_card', 'کارت به کارت'), ('other', 'سایر')], default='card_to_card', max_length=20, null=True, verbose_name='روش پرداخت')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('transaction_date', models.DateTimeField(verbose_name='تاریخ تراکنش')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.customer', verbose_name='مشتری')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.employee', verbose_name='کارمند')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_transactions', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ('-transaction_date',),
            },
        ),
    ]
