# Generated by Django 6.0.7 on 2026-08-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_employee_national_code_alter_role_table'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('last_number', models.PositiveIntegerField(default=99, verbose_name='آخرین شماره سفارش')),
            ],
            options={
                'verbose_name': 'شمارنده روزانه سفارش',
                'verbose_name_plural': 'شمارنده\u200cهای روزانه سفارش',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نوع سفارش')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'نوع سفارش',
                'verbose_name_plural': 'نوع\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(verbose_name='شماره سفارش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('discount', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف')),
                ('tax', models.PositiveBigIntegerField(default=0, verbose_name='مالیات')),
                ('packaging_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه بسته\u200cبندی')),
                ('total_price', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کل')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.customer', verbose_name='مشتری')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.ordertype', verbose_name='نوع سفارش')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.PositiveBigIntegerField(verbose_name='قیمت واحد')),
                ('total_price', models.PositiveBigIntegerField(verbose_name='جمع')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_date', 'order_number'), name='unique_order_number_per_day'),
        ),
    ]
