# Generated by Django 6.0.7 on 2026-08-22 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default=django.utils.timezone.localdate, verbose_name='شماره سفارش'),
        ),
    ]
