# Generated by Django 6.0.7 on 2026-08-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_date_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره میز'),
        ),
    ]
