# Generated by Django 6.0.7 on 2026-08-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0004_order_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت بانکی'), ('card_to_card', 'کارت به کارت'), ('credit', 'نسیه'), ('free', 'رایگان'), ('staff_meal', 'غذای پرسنل'), ('unknown', 'نامعلوم')], default='unknown', max_length=20, verbose_name='روش پرداخت')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداختها',
                'ordering': ('-payment_date',),
            },
        ),
    ]
